package com.zhiroke.jetwallet.ui.theme

import androidx.compose.ui.graphics.Color

/** Material 3 light colors palette */
val LightPrimary = Color(0xFF714D9F)
val White = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFEEDCFF)
val LightOnPrimaryContainer = Color(0xFF2A0054)
val LightSecondary = Color(0xFF00658F)
val LightSecondaryContainer = Color(0xFFC7E7FF)
val LightOnSecondaryContainer = Color(0xFF001E2E)
val LightTertiary = Color(0xFF006A64)
val LightTertiaryContainer = Color(0xFFFFDAD6)
val LightOnTertiaryContainer = Color(0xFF00201D)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF1D1B1E)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF1D1B1E)
val LightOutline = Color(0xFF7B757F)
val LightSurfaceVariant = Color(0xFFE8E0EB)
val LightOnSurfaceVariant = Color(0xFF4A454E)

/** Material 3 dark colors palette */
val DarkPrimary = Color(0xFFD9B9FF)
val DarkOnPrimary = Color(0xFF401B6D)
val DarkPrimaryContainer = Color(0xFF583485)
val DarkOnPrimaryContainer = Color(0xFFEEDCFF)
val DarkSecondary = Color(0xFF86CFFF)
val DarkOnSecondary = Color(0xFF00344C)
val DarkSecondaryContainer = Color(0xFF004C6D)
val DarkOnSecondaryContainer = Color(0xFFC7E7FF)
val DarkTertiary = Color(0xFF50DBCF)
val DarkOnTertiary = Color(0xFF003733)
val DarkTertiaryContainer = Color(0xFF00504B)
val DarkOnTertiaryContainer = Color(0xFF71F7EB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1D1B1E)
val DarkOnBackground = Color(0xFFE7E1E5)
val DarkSurface = Color(0xFF1D1B1E)
val DarkOnSurface = Color(0xFFE7E1E5)
val DarkOutline = Color(0xFF958E99)
val DarkSurfaceVariant = Color(0xFF4A454E)
val DarkOnSurfaceVariant = Color(0xFFCCC4CF)