object Versions {
    const val kotlin = "1.6.21"
    const val koin = "3.2.2"
    const val room = "2.4.3"
    const val sqlcipher = "4.5.0@aar"
    const val navigation = "2.5.0"
    const val coroutines = "1.5.2"
    const val cameraX = "1.2.0"
    const val cameraXMlKit = "1.2.0-beta02"
    const val textRecognizerMlKit = "18.0.2"
    const val lifecycle = "2.6.0-alpha01"
    const val compose = "1.2.1"
    const val composeCompiler = "1.3.2"
    const val accompanist = "0.28.0"
    const val material3 = "1.1.0-alpha02"
}